import type { GameDefinition } from "./types";

export const GAME_CATALOG: GameDefinition[] = [
  {
    id: "category-challenge",
    title: { ar: "تحدّي الفئات", en: "Category Challenge" },
    description: {
      ar: "تسابقوا لذكر إجابات تنتمي إلى الفئة قبل انتهاء الوقت.",
      en: "Race to name answers that fit the category before time runs out.",
    },
    emoji: "🗂️",
    playerRange: { min: 2, max: 12 },
    approximateMinutes: 15,
    supportedModes: ["local", "room"],
    art: { src: "/games/category-challenge.png", alt: { ar: "بطاقات أسئلة وتاج التحدّي", en: "Quiz cards and a challenge crown" }, accent: "#E5A93D" },
    contentFamilies: ["knowledge", "arab-world", "islamic"],
  },
  {
    id: "out-of-loop",
    title: { ar: "برا السالفة", en: "Out of the Loop" },
    description: {
      ar: "اكتشفوا من لا يعرف الكلمة السرية قبل أن يكتشفها هو.",
      en: "Find the player who does not know the secret word before they figure it out.",
    },
    emoji: "🕵️",
    playerRange: { min: 3, max: 12 },
    approximateMinutes: 15,
    supportedModes: ["local", "room"],
    art: { src: "/games/out-of-loop.png", alt: { ar: "دائرة حوار وفيها شخص خارج السالفة", en: "A conversation circle with one player out of the loop" }, accent: "#A9D5C2" },
    contentFamilies: ["everyday", "arab-world", "family"],
  },
  {
    id: "charades",
    title: { ar: "تمثيل صامت", en: "Charades" },
    description: {
      ar: "مثّل الكلمة من دون كلام ودع فريقك يحزرها.",
      en: "Act out the word without speaking and let your team guess it.",
    },
    emoji: "🎭",
    playerRange: { min: 4, max: 16 },
    approximateMinutes: 20,
    supportedModes: ["local", "room"],
    art: { src: "/games/charades.png", alt: { ar: "أقنعة وأيادٍ تمثّل بصمت", en: "Theatre masks and expressive hands" }, accent: "#6E4E72" },
    contentFamilies: ["performance", "family", "arab-world"],
  },
  {
    id: "forbidden-word",
    title: { ar: "الكلمة الممنوعة", en: "Forbidden Word" },
    description: {
      ar: "اشرح الكلمة لفريقك من دون استخدام الكلمات الممنوعة.",
      en: "Describe the target to your team without using the forbidden words.",
    },
    emoji: "🚫",
    playerRange: { min: 4, max: 16 },
    approximateMinutes: 20,
    supportedModes: ["local", "room"],
    art: { src: "/games/forbidden-word.png", alt: { ar: "فقاعات كلام وإشارة منع", en: "Speech bubbles with a playful stop sign" }, accent: "#D8674B" },
    contentFamilies: ["words", "family", "arab-world"],
  },
  {
    id: "who-am-i",
    title: { ar: "من أنا؟", en: "Who Am I?" },
    description: {
      ar: "اطرح أسئلة بنعم أو لا لتعرف الشخصية المخفية.",
      en: "Ask yes-or-no questions to discover your hidden identity.",
    },
    emoji: "❓",
    playerRange: { min: 2, max: 12 },
    approximateMinutes: 15,
    supportedModes: ["local", "room"],
    art: { src: "/games/who-am-i.png", alt: { ar: "شخصية غامضة وبطاقة سؤال", en: "A mystery identity and question card" }, accent: "#6E4E72" },
    contentFamilies: ["people", "arab-world", "islamic-civilization"],
  },
  {
    id: "rapid-fire",
    title: { ar: "إجابات سريعة", en: "Rapid Fire" },
    description: {
      ar: "أجب عن أكبر عدد من الأسئلة قبل انتهاء العدّ التنازلي.",
      en: "Answer as many prompts as possible before the countdown ends.",
    },
    emoji: "⚡",
    playerRange: { min: 2, max: 12 },
    approximateMinutes: 10,
    supportedModes: ["local", "room"],
    art: { src: "/games/rapid-fire.png", alt: { ar: "برق ونبض للإجابات السريعة", en: "Lightning and a pulse for rapid answers" }, accent: "#E5A93D" },
    contentFamilies: ["quick", "knowledge", "family"],
  },
  {
    id: "most-likely-to",
    title: { ar: "مين الأكثر احتمالاً؟", en: "Most Likely To" },
    description: {
      ar: "صوّتوا للشخص الأكثر احتمالاً أن ينطبق عليه السؤال.",
      en: "Vote for the person most likely to match each prompt.",
    },
    emoji: "👉",
    playerRange: { min: 3, max: 16 },
    approximateMinutes: 15,
    supportedModes: ["local", "room"],
    art: { src: "/games/most-likely-to.png", alt: { ar: "مجموعة تشير إلى لاعب", en: "A group pointing toward one player" }, accent: "#46D7B8" },
    contentFamilies: ["social", "family", "friends"],
  },
  {
    id: "two-truths-lie",
    title: { ar: "حقيقتان وكذبة", en: "Two Truths and a Lie" },
    description: {
      ar: "شارك ثلاث جمل عن نفسك ودع الآخرين يكتشفون الكذبة.",
      en: "Share three statements about yourself and let the others spot the lie.",
    },
    emoji: "🤥",
    playerRange: { min: 3, max: 12 },
    approximateMinutes: 20,
    supportedModes: ["local", "room"],
    art: { src: "/games/two-truths-lie.png", alt: { ar: "ثلاث بطاقات وواحدة مختلفة", en: "Three statement cards with one different card" }, accent: "#6E4E72" },
    contentFamilies: ["social", "personal", "friends"],
  },
];
